remote_theme: just-the-docs/just-the-docs
title: Dark Autumn
description: A Sci-Fi Web Serial
disqus: boltfromtheblue.disqus.com
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
url: boltfromthe.blue
