remote_theme: just-the-docs/just-the-docs
title: Dark Autumn
description: A Sci-Fi Web Serial
disqus: boltfromtheblue.disqus.com
exclude:
  - LICENSE
  - README.md
  - CNAME
excerpt_separator: <!--more-->
timezone: America/Denver
search_enabled: true
search.previews: 5
search.preview_words_before: 5
search.preview_words_after: 10
